import sec1 from "./assets/images/sec1.jpg";
import sec2 from "./assets/images/sec2.jpg";
import sec3 from "./assets/images/sec3.jpg";
import sec4 from "./assets/images/sec4.jpg";
import sec5 from "./assets/images/sec5.jpg";
import sec6 from "./assets/images/sec6.jpg";
import sec7 from "./assets/images/sec7.jpg";

export const data = [
  {
    id: 1,
    name: "Improved Kienyeji",
    image: sec1,
    price: 400.0,
    prevPrice: 500.0,
    sect: "Section A",
    totalCount: 26,
    age: "5 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 2,
    name: "Improved Kienyeji and pure kienyeji",
    image: sec2,
    price: 800.0,
    prevPrice: 900.0,
    sect: "Section B",
    totalCount: 15,
    age: "6 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 3,
    name: "Improved Kienyeji",
    image: sec3,
    price: 1000.0,
    prevPrice: 1500.0,
    sect: "Section C",
    totalCount: 10,
    age: "7 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 4,
    name: "Improved Kienyeji",
    image: sec4,
    price: 600.0,
    prevPrice: 650.0,
    sect: "Section D",
    totalCount: 13,
    age: "6 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 5,
    name: "Improved Kienyeji",
    image: sec5,
    price: 500.0,
    prevPrice: 600.0,
    sect: "Section E",
    totalCount: 18,
    age: "5 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 6,
    name: "Improved Kienyeji",
    image: sec6,
    price: 900.0,
    prevPrice: 1000.0,
    sect: "Section F",
    totalCount: 26,
    age: "6 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
  {
    id: 7,
    name: "Improved Kienyeji",
    image: sec7,
    price: 700.0,
    prevPrice: 850.0,
    sect: "Section G",
    totalCount: 25,
    age: "5 months",
    vaccintion: "2 weeks ago",
    addedBy: "Emonyi",
    desdcription: "Lays eggs daily.",
  },
];
